# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 14

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./gradlew build test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: obsidian-startpage
          path: obsidian-startpage/generated/obsidian-startpage.jar
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
          if-no-files-found: # optional, default is warn